name: sonar_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy<2
  - pytorch=2.0.1=py3.9_cuda11.8_cudnn8.6.0_0  # match GPU and CUDA
  - torchvision=0.15.2=py39_cu118_default
  - torchaudio=2.0.2
  - detectron2=0.6 # conda channel detectron2
  - opencv
  - albumentations
  - pip:
    - git+https://github.com/thuml/Transfer-Learning-Library.git
