name: sonar_env
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy<2
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - opencv
  - albumentations
  - pip:
    - git+https://github.com/thuml/Transfer-Learning-Library.git
