# -*- coding: utf-8 -*-
"""loss_wrappers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFM8IB-8q8tizgbWzcWTdFIB0oE7J8yo
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from tllib.alignment.dann import DomainAdversarialLoss

class SafeDomainAdversarialLoss(DomainAdversarialLoss):
    def forward(self, f_s, f_t):
        logits_s = self.domain_discriminator(f_s)
        logits_t = self.domain_discriminator(f_t)
        domain_label_s = torch.ones_like(logits_s)
        domain_label_t = torch.zeros_like(logits_t)
        domain_label = torch.cat((domain_label_s, domain_label_t), dim=0)
        domain_pred = torch.cat((logits_s, logits_t), dim=0)
        return F.binary_cross_entropy_with_logits(domain_pred, domain_label)