# -*- coding: utf-8 -*-
"""evaluate_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XM6LbxbmGFxvKaZltXvxi2V1nko01_HD
"""

import os
import torch
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
from torchmetrics.detection.mean_ap import MeanAveragePrecision
from voc_dataset import VOCDataset

def evaluate(model, dataset_root, batch_size=4, image_set="val"):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.eval()
    model.to(device)

    # Load trained weights if available
    weight_path = "checkpoints/baseline_sonar_fasterrcnn.pth"
    if os.path.exists(weight_path):
        model.load_state_dict(torch.load(weight_path, map_location=device))
        print("Loaded model weights from:", weight_path)
    else:
        print("No weights found. Using default model weights.")

    dataset = VOCDataset(dataset_root, image_set=image_set, transforms=ToTensor())
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, collate_fn=lambda x: tuple(zip(*x)))

    metric = MeanAveragePrecision()

    with torch.no_grad():
        for imgs, targets in loader:
            imgs = list(img.to(device) for img in imgs)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            outputs = model(imgs)

            preds = []
            targs = []
            for o, t in zip(outputs, targets):
                preds.append({
                    "boxes": o["boxes"].cpu(),
                    "scores": o["scores"].cpu(),
                    "labels": o["labels"].cpu()
                })
                targs.append({
                    "boxes": t["boxes"].cpu(),
                    "labels": t["labels"].cpu()
                })

            metric.update(preds, targs)

    results = metric.compute()
    print("Evaluation Results:")
    for k, v in results.items():
        print(f"{k}: {v:.4f}")

# Call the function
evaluate(model, "/content/drive/MyDrive/sonar-object-detection/data/line2voc")