# -*- coding: utf-8 -*-
"""train_augmented_fasterrcnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QexoRF5jocki-wOZCSBtKvIBeARTEScs
"""

# train Faster R-CNN on CLAHE + augmented sonar images (Colab version)

import sys
import os
import torch
from tqdm import tqdm
from torch.utils.data import DataLoader
from torchvision import transforms as T
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

# allow importing my custom dataset class
sys.path.append('/content/drive/MyDrive/sonar-object-detection/scripts')
from voc_dataset import VOCDataset

# dataset path (this one was denoised + enhanced + augmented offline)
DATASET_DIR = "/content/drive/MyDrive/sonar-object-detection/data/line2voc_preprocessed_augmented"

# just normalize and convert to tensor
transform = T.ToTensor()

# load train and val splits
train_dataset = VOCDataset(DATASET_DIR, image_set="train", transforms=transform)
val_dataset = VOCDataset(DATASET_DIR, image_set="val", transforms=transform)

train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True, collate_fn=lambda x: tuple(zip(*x)))
val_loader = DataLoader(val_dataset, batch_size=2, shuffle=False, collate_fn=lambda x: tuple(zip(*x)))

# load model with pretrained weights
model = fasterrcnn_resnet50_fpn(weights="DEFAULT")
in_features = model.roi_heads.box_predictor.cls_score.in_features

# change head for 2 object classes + background
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, 3)

# move model to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# optimizer
params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.AdamW(params, lr=1e-4)

# training loop
num_epochs = 5
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for imgs, targets in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        imgs = [img.to(device) for img in imgs]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(imgs, targets)
        losses = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

        running_loss += losses.item()

    print(f"Epoch {epoch+1}, Loss: {running_loss:.4f}")

# save model
SAVE_PATH = "/content/drive/MyDrive/sonar-object-detection/checkpoints/augmented_fasterrcnn.pth"
torch.save(model.state_dict(), SAVE_PATH)
print(f"Model saved to: {SAVE_PATH}")